[package]
name = "sp-ark-bls12-381"
version = "0.4.0"
authors = [ "achimcc, arkworks contributors" ]
repository = "https://github.com/paritytech/substrate/"
description = "The BLS12-381 pairing-friendly elliptic curve, optimized for Substrate"
keywords = ["cryptography", "finite-fields", "elliptic-curves" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-std = { version = "0.4.0-alpha", default-features = false }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-bls12-381 = { git = "https://github.com/arkworks-rs/curves", default-features = false, features = ["curve"] }
ark-models = { path = "../../arkworks-models", default-features = false }
sp-io = { path = "../../io", default-features = false }

[dev-dependencies]
ark-algebra-test-templates = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
hex = "^0.4.0"

[features]
default = [ "curve" ]
std = [ "ark-std/std", "ark-ff/std", "ark-models/std", "ark-bls12-381/std", "ark-serialize/std", "sp-io/std" ]
curve = [ "scalar_field", "base_field" ]
scalar_field = []
base_field = []

