[package]
name = "ark-sub-bw6-761"
version = "0.4.0-alpha.1"
authors = [ "achimcc, arkworks contributors" ]
description = "The BW6-761 pairing-friendly elliptic curve, optimized for Substrate"
keywords = ["cryptography", "finite-fields", "elliptic-curves" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
ark-ff = { version="0.4.0-alpha", default-features = false }
ark-std = { version = "0.4.0-alpha", default-features = false }
ark-bw6-761 = { git = "https://github.com/arkworks-rs/curves" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-sub-bls12-377 = { version = "0.4.0-alpha", path = "../bls12_377", default-features = false, features = [ "base_field" ] }
ark-models = { path = "../../arkworks-models" }
sp-io = { path = "../../io" }

[dev-dependencies]
ark-algebra-test-templates = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }

[features]
default = []
std = [ "ark-std/std", "ark-ff/std", "ark-ec/std", "ark-sub-bls12-377/std" ]

