[package]
name = "ark-ed-on-bls12-377"
version = "0.4.0-alpha.1"
authors = [ "arkworks contributors" ]
description = "A Twisted Edwards curve defined over the scalar field of the BLS12-377 curve"
homepage = "https://arkworks.rs"
repository = "https://github.com/arkworks-rs/curves"
documentation = "https://docs.rs/ark-ed-on-bls12-377/"
keywords = ["cryptography", "finite-fields", "elliptic-curves" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
ark-ff = { version = "0.4.0-alpha", default-features = false }
ark-std = { version = "0.4.0-alpha", default-features = false }
ark-ed-on-bls12-377 = { git = "https://github.com/arkworks-rs/curves" }
ark-r1cs-std = { version = "0.4.0-alpha", default-features = false, optional = true }
ark-sub-bls12-377 = { version = "0.4.0-alpha", path = "../bls12_377", default-features = false, features = [ "scalar_field" ] }
ark-models = { path = "../../arkworks-models" }

[dev-dependencies]
ark-relations = { version = "0.4.0-alpha", default-features = false }
ark-serialize = { version = "0.4.0-alpha", default-features = false }
ark-algebra-test-templates = { version = "0.4.0-alpha", default-features = false }
ark-curve-constraint-tests = { path = "../curve-constraint-tests", default-features = false }

[features]
default = []
std = [ "ark-std/std", "ark-ff/std", "ark-models/std", "ark-sub-bls12-377/std" ]
r1cs = [ "ark-r1cs-std" ]
