[package]
name = "sp-ark-ed-on-bls12-377"
version = "0.4.0-alpha.1"
authors = [ "achimcc, arkworks contributors" ]
repository = "https://github.com/paritytech/substrate/"
description = "A Twisted Edwards curve defined over the scalar field of the BLS12-377 curve, optimized for Substrate"
keywords = ["cryptography", "finite-fields", "elliptic-curves" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
ark-ff = { version = "0.4.0-alpha", default-features = false }
ark-std = { version = "0.4.0-alpha", default-features = false }
ark-ed-on-bls12-377 = { git = "https://github.com/arkworks-rs/curves" }
ark-serialize = { version = "0.4.0-alpha", default-features = false }
ark-r1cs-std = { version = "0.4.0-alpha", default-features = false, optional = true }
sp-ark-bls12-377 = { version = "0.4.0-alpha", path = "../bls12_377", default-features = false, features = [ "scalar_field" ] }
ark-models = { path = "../../arkworks-models" }
sp-io = { path = "../../io" }

[dev-dependencies]
ark-relations = { git = "https://github.com/arkworks-rs/snark", default-features = false }
ark-algebra-test-templates = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-curve-constraint-tests = { path = "../curve-constraint-tests", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }

[features]
default = []
std = [ "ark-std/std", "ark-ff/std", "ark-models/std", "sp-ark-bls12-377/std" ]
r1cs = [ "ark-r1cs-std" ]
