[package]
name = "pallet-fast-unstake"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME fast unstake pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }

frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" }

sp-io = { version = "7.0.0", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "7.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "5.0.0", default-features = false, path = "../../primitives/std" }
sp-staking = { default-features = false, path = "../../primitives/staking" }
frame-election-provider-support = { default-features = false, path = "../election-provider-support" }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../benchmarking" }

pallet-staking-reward-curve = { version = "4.0.0-dev", path = "../staking/reward-curve", optional = true }
sp-core = { version = "7.0.0", default-features = false, path = "../../primitives/core", optional = true }
substrate-test-utils = { version = "4.0.0-dev", path = "../../test-utils", optional = true }
sp-tracing = { version = "6.0.0", path = "../../primitives/tracing", optional = true }
pallet-staking = { path = "../staking", optional = true }
pallet-balances = { path = "../balances", optional = true }
pallet-timestamp = { path = "../timestamp", optional = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",

	"frame-support/std",
	"frame-system/std",

	"sp-io/std",
	"sp-staking/std",
	"sp-runtime/std",
	"sp-std/std",

	"frame-election-provider-support/std",

	"frame-benchmarking/std",

	"pallet-staking-reward-curve",
	"sp-core",
	"substrate-test-utils",
	"sp-tracing",
	"pallet-staking",
	"pallet-balances",
	"pallet-timestamp"
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
